version: "3"

services:
  broker:
    container_name: eclipse-mosquitto
    privileged: true
    image: "eclipse-mosquitto:latest"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
  serial-mon:
    container_name: serial-mon
    privileged: true
    image: "arupiot/dummy-gateway:demo"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - HOSTNAME
    restart: always
